version: "3"

#x-test-service: &test
#  image: python:3-alpine
#  command:
#    - python3
#    - -m
#    - http.server
#    - "8080"
#  labels:
#    - "external-dns-docker/enabled=true"

services:
  app:
    build: .
    command:
      - /external-dns-docker
      - --record-suffix=prv
      - --zone-name=qiu.casa
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    privileged: true
    env_file:
      - .env
